package org.example.model.building.enums;

public enum BuildingCategory {
    TYPES_AND_COMPONENTS_CASTLES,
    FARMS_AND_HUNTING_GROUNDS,
    FOOD_PROCESSING,
    INDUSTRIAL,
    HEADQUARTERS_AND_FORTIFICATIONS,
    TOWERS_AND_GATES,
    URBAN_STRUCTURES,
    MANUFACTURE_AND_MAINTENANCE_OF_WEAPONS,
    TREES;
}
